package = 'org.bonadza.openrtb'
model = {
	'bidResponse' : {
		'id' : 'str',
		'seatbid': [{
			'bid' : [{
				'id' : 'str',
				'impid' : 'str',
				'price' : 'float',
				'adid' : 'str',
				'nurl' : 'str',
				'adm' : 'str',
				'adomain' : 'str[]',
				'bundle' : 'str',
				'iurl' : 'str',
				'cid' : 'str',
				'crid' : 'str',
				'cat' : 'str[]',
				'attr' : 'int[]',
				'dealid' : 'str',
				'w' : 'int',
				'h' : 'int',
				'ext' : 'ext'
			}],
			'seat' : 'str',
			'group' : 'int',
			'ext' : 'ext'
		}],
		'bidid' : 'str',
		'cur' : 'str',
		'customdata' : 'str',
		'nbr' : 'int',
		'ext' : 'ext'
	},
	'bidRequest' : {
		'id' : 'str',
		'imp' : [{
			'id' : 'str',
			'banner' : {
				'w' : 'int',
				'h' : 'int',
				'wmax' : 'int',
				'hmax' : 'int',
				'wmin' : 'int',
				'hmin' : 'int',
				'id' : 'str',
				'btype' : 'int[]',
				'battr' : 'int[]',
				'pos' : 'int',
				'mimes' : 'str[]',
				'topframe' : 'int',
				'expdir' : 'int[]',
				'api' : 'int[]',
				'ext' : 'ext',
			},
			'video' : {
				'mimes' : 'str[]',
				'minduration' : 'int',
				'maxduration' : 'int',
				'protocol' : 'int',
				'protocols' : 'int[]',
				'w' : 'int',
				'h' : 'int',
				'startdelay' : 'int',
				'linearity' : 'int',
				'sequence' : 'int',
				'battr' : 'int[]',
				'maxextended' : 'int',
				'minbitrate' : 'int',
				'maxbitrate' : 'int',
				'boxingallowed' : 'int',
				'playbackmethod' : 'int[]',
				'delivery' : 'int[]',
				'pos' : 'int',
				# 'companionad' : ''
				'api' : 'int[]',
				'ext' : 'ext',
				'companiontype' : 'int[]'
			},
			'native' : {
				'request' : 'str[]',
				'ver' : 'str',
				'api' : 'int[]',
				'battr' : 'int[]',
				'ext' : 'ext'
			},
			'displaymanager' : 'str',
			'displaymanagerver' : 'str',
			'instl' : 'int',
			'tagid' : 'str',
			'bidfloor' : 'float',
			'bidfloorcur' : 'str',
			'secure' : 'int',
			'iframebuster' : 'str[]',
			'pmp' : {
				'private_auction' : 'int',
				'deals' : [{
					'id' : 'str',
					'bidfloor' : 'float',
					'bidfloorcur' : 'str',
					'at' : 'int',
					'wseat' : 'str[]',
					'wadomain' : 'str[]',
					'ext' : 'ext'
				}],
				'ext' : 'ext'
			},
			'ext' : 'ext'
		}],
		'site' : {
			'id' : 'str',
			'name' : 'str',
			'domain' : 'str',
			'cat' : 'str[]',
			'sectioncat' : 'str[]',
			'pagecat' : 'str[]',
			'page' : 'str',
			'ref' : 'str',
			'search' : 'str',
			'mobile' : 'int',
			'privacypolicy' : 'int',
			'publisher' : {
				'id' : 'str',
				'name' : 'str',
				'cat' : 'str[]',
				'domain' : 'str',
				'ext' : 'ext'
			},
			'content' : {

			},
			'keywords' : 'str',
			'ext' : 'ext'
		},
		'app': {
			'id' : 'str',
			'name' : 'str',
			'bundle' : 'str',
			'domain' : 'str',
			'storeurl' : 'str',
			'cat' : 'str[]',
			'sectioncat' : 'str[]',
			'pagecat' : 'str[]',
			'ver' : 'str',
			'privacypolicy' : 'int',
			'paid' : 'int',
			'publisher' : {},
			'content' : {},
			'keywords' : 'str',
			'ext' : 'ext',
		},
		'device' : {
			'ua' : 'str',
			'geo' : {
				'lat' : 'float',
				'lon' : 'float',
				'type' : 'int',
				'country' : 'str',
				'region' : 'str',
				'regionfips104' : 'str',
				'metro' : 'str',
				'city' : 'str',
				'zip' : 'str',
				'utcoffset' : 'int',
				'ext' : 'ext',
			},
			'dnt' : 'int',
			'lmt' : 'int',
			'ip' : 'str',
			'ipv6' : 'str',
			'devicetype' : 'int',
			'make' : 'str',
			'model' : 'str',
			'os' : 'str',
			'osv' : 'str',
			'hwv' : 'str',
			'osv' : 'str',
			'w' : 'int',
			'h' : 'int',
			'js' : 'int',
			'ppi' : 'int',
			'pxratio' : 'float',
			'flashver' : 'str',
			'language' : 'str',
			'carrier' : 'str',
			'connectiontype' : 'int',
			'ifa' : 'str',
			'didsha1' : 'str',
			'didmd5' : 'str',
			'dpidsha1' : 'str',
			'dpidmd5' : 'str',
			'macsha1' : 'str',
			'macmd5' : 'str',
			'ext' : 'ext',
		},
		'user' : {
			'id' : 'str',
			'buyeruid' : 'str',
			'yob' : 'int',
			'gender' : 'str',
			'keywords' : 'str',
			'customdata' : 'str',
			'geo' : {},
			'data' : [{
				'id' : 'str',
				'name' : 'str',
				'segment' : [{
					'id' : 'str',
					'name' : 'str',
					'value' : 'str',
					'ext' : 'ext'
				}],
				'ext' : 'ext'
			}],
			'ext' : 'ext',
		},
		'test' : 'int',
		'at' : 'int',
		'tmax' : 'int',
		'wseat' : 'str[]',
		'allimps' : 'int',
		'cur' : 'str[]',
		'bcat' : 'str[]',
		'badv' : 'str[]',
		'regs' : {
			'coppa' : 'int',
			'ext' : 'ext'
		},
		'ext' : 'ext'
	}
}